name = "pastebin-o1o"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

account_id = "516d0a360ccdea88dd79e9cf5d2bc3aa"
main = "src/index.ts"
workers_dev = false

[vars]
ENVIRONMENT = "production"
BASE_URL = "https://paste.o1o.zip"

[site]
bucket = "./static/dist"

# 如果不使用自定义域名，将下面的代码注释掉
# 1
[[routes]]
pattern = "paste.o1o.zip"
custom_domain = true

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = "pastes-o1o"

[[d1_databases]]
binding = "DB"
database_name = "pastebins-o1o"
database_id = "4d4a4f03-d54d-4460-86d1-603f3f6fe412"
